# Generated by Django 4.0.2 on 2022-09-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsemodel',
            name='questions',
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='questions',
            field=models.ManyToManyField(related_name='question', to='base.QuestionModel'),
        ),
    ]
