# Generated by Django 4.0.2 on 2022-09-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_responsemodel_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='answer',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='answers',
            field=models.ManyToManyField(related_name='answer', to='base.AnswerModel'),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='category',
            field=models.CharField(default='string', max_length=50),
            preserve_default=False,
        ),
    ]
