# Generated by Django 4.0.2 on 2022-09-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_questionmodel_answer_questionmodel_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='test_field',
            field=models.CharField(default='string', max_length=50),
            preserve_default=False,
        ),
    ]
