# Generated by Django 4.0.2 on 2022-09-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_questionmodel_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='test_field',
        ),
    ]
