# Generated by Django 4.0.2 on 2022-09-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_questionmodel_test_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='category',
            field=models.ManyToManyField(related_name='category', to='base.CategoryModel'),
        ),
    ]
